name: Identify Event Type
on: [push, pull_request, issues]

jobs:
  identify-event:
    runs-on: ubuntu-latest
    steps:
      - name: Check Event Name
        run: echo "This workflow was triggered by a ${{ github.event-name }} event."
