name: BD Workflow
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
        ports:
          - 5432:5432
    steps:
    - uses: actions/checkout@v3
